### ISSUE TITLE
info/todo

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/hilbertv4#1]
finally doing this right and using a raster geom plus making it a first-class ggplot2 citizen

- [ ] need to make better parameters 
- [ ] need to allow for CIDR block shading
- [ ] need to allow for CIDR block labeling
- [ ] need to allow for arbitrary labels at any IPv4 position
- [ ] work on the 'fill' to support more than just mapping to continuous count
